name: Build and release app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      env:
        FASTLANE_USER: ${{ secrets.APPLE_MAIL }}
        FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      run: fastlane app
