name: Build and release app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build app
      env:
        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
      run: fastlane app
